config/routes.rb
Rails.application.routes.draw do

  get 'badge_ownerships/show'
  get 'badge_ownerships/index'
  get 'care_takings/new'
  get 'show/sandman'
  # post 'care_takings/create', to: 'care_takings#create', as: "baby_care_takings"
  devise_for :users
  root to: 'pages#home'
  resources :babies, only: [:show, :create, :new] do
      resources :breast_feedings, only: [:create, :new, :show, :index]
      resources :bottle_feedings, only: [:create, :new, :show, :index]
      resources :sleeps, only: [:create, :new, :show, :index]
      resources :care_takings, only: [:create]
      resources :diapers, only: [:create, :new, :show, :index]
      resources :moods, only: [:create, :new, :show, :index]
  end
  resources :feedings, only: [:destroy]
  resources :sleeps, only: [:destroy]
  resources :breast_feedings, only: [:destroy]
  resources :bottle_feedings, only: [:destroy]
  resources :diapers, only: [:destroy]
  resources :users, only: [:show]
  resources :care_takings, only: [:destroy]
  resources :moods, only: [:destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :babies, dependent: :destroy
  has_many :diapers, dependent: :destroy
  has_many :sleeps, dependent: :destroy
  has_many :badge_ownerships, dependent: :destroy
  has_many :care_takings
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @babies = current_user.babies
    @baby = @babies.first
  end
end

app/views/users/show.html.erb
<div class="back-close-nav">
 <%= link_to baby_path(@baby.id) do %>

 <img src="<%= image_path('back-arrow.svg') %>" alt=""></div>
</div>
<% end %>


<div class="container">
  <div class="user-information" style="display: flex: flex-wrap: wrap;">
    <h1><%= current_user.name %>'s profil</h1>
      <div class="d-flex flex-column align-items-center">
        <img src="<%= image_path('moi.jpg') %>" alt="" style="width:90px; margin:25px; border-radius: 80px;">
        <p class="edit-profil">edit your profil</p>
      </div>
  </div>

  <% if @babies.any?  %>
    <% @babies.each do |b|  %>

      <button class="accordion baby-accordion">
        <h2><span><%=b.name%> <i class="fas fa-angle-down"></i></span></h2>
      </button>

        <div class="panel">
          <p class="shared-access-title">Shared access with:</p>
            <% b.care_takings.each do |c|%>
              <div class="caretaker-info">

                <div class="caretaker-contact">
                  <p class="caretaker-name"><%= c.name %></p>
                  <p class="caretaker-email"><%= c.email %></p>
                </div>
                 <%= link_to care_taking_path(c), method: :delete do %>
                  <img src="<%= image_path('close.svg') %>" alt="" style="width:10px">
                  <% end %>
              </div>
            <% end %>

              <div class="care_taking_form">
                <%= simple_form_for [b, CareTaking.new], method: :post, url: baby_care_takings_path(b) do |f| %>
                  <%= f.input :name, placeholder: "Name", label: false %>
                  <%= f.input :email, placeholder: "Email", label: false %>
                  <%= f.submit("Share Access", class: "button-blue-share") %>
                <% end %>
              </div>
        </div>
    <% end %>
  <% end %>


<button class="accordion caretaking-baby-accordion">
  <h2>babies shared with you <i class="fas fa-angle-down"></i></h2>
</button>

  <div class="panel">

    <% if current_user.care_takings.count > 0 %>
    <% current_user.care_takings.each do |care_taking| %>
      <div class="caretaking-baby-card">
        <p class="caretaking-baby-name"><%= link_to care_taking.baby.name, baby_path(care_taking.baby) %></p>

        <div class="caretaking-baby-info">
          <p>birthday : <%= care_taking.baby.birthdate %></p>
        </div>


      </div>

    <!-- </div> -->

      <% end %>
    <% end %>



  </div>

</div>

<script>
  var acc = document.getElementsByClassName("accordion");
  var i;

  for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var panel = this.nextElementSibling;
      if (panel.style.maxHeight) {
        panel.style.maxHeight = null;
      } else {
        panel.style.maxHeight = panel.scrollHeight + "px";
      }
    });
  }
</script>