config/routes.rb
Rails.application.routes.draw do

  get 'badge_ownerships/show'
  get 'badge_ownerships/index'
  get 'care_takings/new'
  get 'show/sandman'
  # post 'care_takings/create', to: 'care_takings#create', as: "baby_care_takings"
  devise_for :users
  root to: 'pages#home'
  resources :babies, only: [:show, :create, :new] do
      resources :breast_feedings, only: [:create, :new, :show, :index]
      resources :bottle_feedings, only: [:create, :new, :show, :index]
      resources :sleeps, only: [:create, :new, :show, :index]
      resources :care_takings, only: [:create]
      resources :diapers, only: [:create, :new, :show, :index]
      resources :moods, only: [:create, :new, :show, :index]
  end
  resources :feedings, only: [:destroy]
  resources :sleeps, only: [:destroy]
  resources :breast_feedings, only: [:destroy]
  resources :bottle_feedings, only: [:destroy]
  resources :diapers, only: [:destroy]
  resources :users, only: [:show]
  resources :care_takings, only: [:destroy]
  resources :moods, only: [:destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <%= link_to badge_ownerships_index_path, class: "navbar-brand" do %>
    <img src="<%= image_path('medal.svg') %>" alt="" style= "width: 35px;">
  <% end %>

  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "thomas_logo_2.png" %>
  <% end %>


  <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <img src="<%= image_path('user.svg') %>" alt="" style= "width: 30px;">
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Profil", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>