config/routes.rb
Rails.application.routes.draw do

  get 'badge_ownerships/show'
  get 'badge_ownerships/index'
  get 'care_takings/new'
  get 'show/sandman'
  # post 'care_takings/create', to: 'care_takings#create', as: "baby_care_takings"
  devise_for :users
  root to: 'pages#home'
  resources :babies, only: [:show, :create, :new] do
      resources :breast_feedings, only: [:create, :new, :show, :index]
      resources :bottle_feedings, only: [:create, :new, :show, :index]
      resources :sleeps, only: [:create, :new, :show, :index]
      resources :care_takings, only: [:create]
      resources :diapers, only: [:create, :new, :show, :index]
      resources :moods, only: [:create, :new, :show, :index]
  end
  resources :feedings, only: [:destroy]
  resources :sleeps, only: [:destroy]
  resources :breast_feedings, only: [:destroy]
  resources :bottle_feedings, only: [:destroy]
  resources :diapers, only: [:destroy]
  resources :users, only: [:show]
  resources :care_takings, only: [:destroy]
  resources :moods, only: [:destroy]

end

app/models/baby.rb
class Baby < ApplicationRecord
  belongs_to :user
  has_many :breast_feedings, dependent: :destroy
  has_many :bottlefeedings, dependent: :destroy
  has_many :diapers, dependent: :destroy
  has_many :sleeps, dependent: :destroy
  has_many :moods, dependent: :destroy

  validates :name, :birthdate, presence: true
  has_many :care_takings
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  def index
    @babies = current_user.babies
  end

  def show
    @baby = Baby.find(params[:id])
    @bottlefeedings = @baby.bottlefeedings
    @breastfeedings = @baby.breast_feedings
    @diapers = @baby.diapers
    @sleeps = @baby.sleeps
    @moods = @baby.moods

    @feedings = []

    @bottlefeedings.each do |b|
      feeding = {
        type: "bottle",
        quantity: "#{b.quantity}ml",
        start_date: b.start_date,
        id: b.id,
        user_id: b.user_id
      }
      @feedings << feeding
    end

    @breastfeedings.each do |b|
      feeding = {
        type: "boob",
        duration_minutes: "#{b.duration_minutes}min",
        start_date: b.start_date,
        id: b.id,
        user_id: b.user_id
      }

    @feedings << feeding
    end

    @diapers.each do |b|
      diaper = {
        type: "diaper",
        category: "#{b.category}",
        start_date: b.start_date,
        id: b.id,
        user_id: b.user_id
      }

      @feedings << diaper
    end

    @moods.each do |b|
      mood = {
        type: "mood",
        category: "#{b.category}",
        start_date: b.start_date,
        id: b.id,
        user_id: b.user_id
      }
      @feedings << mood
    end

    @sleeps.each do |b|
      feeding = {
        type: "sleep",
        sleep_time: "#{b.sleep_time}",
        start_date: b.start_date,
        id: b.id,
        user_id: b.user_id
      }

      @feedings << feeding
    end
    @feedings = @feedings.sort_by { |f| f[:start_date] }.reverse!
  end

  def new
    @baby = Baby.new
  end

  def create
    @baby = Baby.new(params_private_baby)
    @baby.user = current_user
    if @baby.save
      redirect_to user_path(current_user)
    else
      render "new_baby"
    end
  end

  private

  def params_private_baby
    params.require(:baby).permit(:name, :birthdate)
  end
end

app/views/babies/component.show.html.erb
<h1>CECI EST LA PAGE AVEC LES COMPONENTS, NE RIEN CODER, CE N'EST PAS LA HOME PAGE</h1>
<%= link_to "Go to breastfeeding", new_baby_breast_feeding_path(@baby) %>
<%= link_to "Go to bottlefeeding", new_baby_bottle_feeding_path(@baby) %>
<br>
<br>
<br>

<div class="back-close-nav">
  <div><a href="/"><img src="<%= image_path('back-arrow.svg') %>" alt="" style="width:25px; margin:25px"></a></div>
  <div><a href="/"><img src="<%= image_path('close.svg') %>" alt="" style="width:25px; margin:25px"></a></div>
</div>
<br>
<br>
<br>
<h1 style="text-align:center">Category Selector</h1>
<div class="category-selector">
  <div class="category-card">
    <img src="<%= image_path('baby-bottle.svg') %>" alt="">
    <div><p>125ml</p></div>
  </div>
  <div class="category-card">
    <img src="<%= image_path('moon.svg') %>" alt="">
    <div><p>4.5h</p></div>
  </div>
  <div class="category-card">
    <img src="<%= image_path('give.svg') %>" alt="">
    <div><p>Happy</p></div>
  </div>
  <div class="category-card">
    <img src="<%= image_path('diaper.svg') %>" alt="">
    <div><p>4 changes</p></div>
  </div>
</div>
<br>
<h1 style="text-align:center">Time selector</h1>
<div class="time-selector">
<div class="button-blue-small">+5min</div>
<div class="button-blue-small">+10min</div>
<div class="button-blue-small">+15min</div>
<div class="button-blue-small">+20min</div>
</div>
<br>
<h1 style="text-align:center">Navigation buttons</h1>
<div class="button-blue-large">Accept</div>
<div class="button-yellow-small">Reset</div>
<div class="button-red-large">Cancel</div>
<div class="button-red-small">Cancel</div>
<br>
<h1 style="text-align:center">Text fields</h1>
<input class="textfield-rounded" id="email-box" placeholder="Email"></div>
<input class="textfield-rounded" id="name-box" placeholder="Name"></div>
<br>
<h1 style="text-align:center">Toggle access</h1>
<div class="toggle-switch">
  <div>
    <p>Nany Louisia</p>
  </div>
  <div class="custom-control custom-switch">
    <input type="checkbox" class="custom-control-input" id="customSwitch1">
    <label class="custom-control-label" for="customSwitch1"></label>
  </div>
</div>

<div class="down-arrow"><img src="<%= image_path('down-arrow.svg') %>" alt=""></div>

<h1 style="text-align:center">Log row</h1>

<div class="log-row">
  <div><img src="<%= image_path('baby-bottle.svg') %>" alt="" style="width:30px"></div>
  <div><p>150ml</p></div>
  <div><p>14H00</p></div>
  <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
</div>
<hr>
<div class="log-row">
  <div><img src="<%= image_path('baby-bottle.svg') %>" alt="" style="width:30px"></div>
  <div><p>150ml</p></div>
  <div><p>14H00</p></div>
  <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
</div>
<hr>
<h1>Text links</h1>
<a href="#">Log in</a>

<hr>

<h1>Babies infos</h1>
<div>
  <div class="baby-info">
    <div><p>Name</p></div> <div><p>Athena</p></div>
  </div>
  <div class="baby-info">
    <div><p>Birthdate</p></div> <div><p>10/12/18</p></div>
  </div>
</div>

app/views/babies/index.html.erb
<%= link_to "More info" , baby_path(@babies[1])%>
<%= render 'shared/navbar' %>

app/views/babies/show.html.erb
<% content_for :meta_title, "THOMAS is looking after #{@baby.name}!" %>
<% content_for :meta_description, 'THOMAS helps you track information about your baby.' %>
<% content_for :meta_image, image_url("cover.png") %>

<%= render 'shared/navbar' %>

<div class="dropdown" style="text-align:center;">

  <button class="btn btn-white dropdown-toggle" type="button" data-toggle="dropdown">
    <h1 style="text-align:center; padding-bottom: 0; margin: 0;">
      <%= @baby.name %>
    </h1>
    <span class="caret"></span>
  </button>

  <ul class="dropdown-menu" style="text-align:center;">
    <% current_user.babies.each do |b|  %>
      <%= link_to baby_path do %>
        <li><h2><%= b.name %></h2></li>
      <% end %>
    <% end %>
  </ul>

</div>

<div class="category-selector">

 <%= link_to baby_bottle_feedings_path(@baby) do %>
  <div class="category-card">
    <img src="<%= image_path('baby-bottle.svg') %>" alt="">
    <div><p>125ml</p></div>
  </div>
<% end %>
<%= link_to baby_sleeps_path(@baby) do %>
  <div class="category-card">
    <img src="<%= image_path('moon.svg') %>" alt="">
    <div><p>4.5h</p></div>
  </div>
<% end %>
<%= link_to baby_moods_path(@baby) do %>
    <div class="category-card">
      <img src="<%= image_path('give.svg') %>" alt="">
      <div><p>Happy</p></div>
    </div>
<% end %>
  <%= link_to baby_diapers_path(@baby) do %>
    <div class="category-card">
      <img src="<%= image_path('diaper.svg') %>" alt="">
      <div><p>4 changes</p></div>
    </div>
  <% end %>

</div>

<div class="time-selector">
  <div class="button-blue-small"> <%= link_to "Bottle", new_baby_bottle_feeding_path(@baby) %></div>
  <div class="button-blue-small"> <%= link_to "Breast", new_baby_breast_feeding_path(@baby) %></div>
</div>

<div class="button-blue-large"><%= link_to "Sleep", new_baby_sleep_path(@baby) %></div>
<div class="button-blue-large"><%= link_to "Mood", new_baby_mood_path(@baby) %></div>
<div class="button-blue-large"> <%= link_to "Diapers", new_baby_diaper_path(@baby) %></div>

<div class="down-arrow" style="margin-top: 25px"><img src="<%= image_path('down-arrow.svg') %>" alt=""></div>

<h1 style="text-align:center">Last logs</h1>

<% @feedings = @feedings.first(20) %>
<% @feedings.each do |f| %>

  <div class="log-row">
    <% if f[:type] == "bottle" %>
      <div><img src="<%= image_path('baby-bottle.svg') %>" alt="" style="width:30px"></div>
      <div><p><%= f[:quantity] %></p></div>
      <div><p><%= User.find(f[:user_id]).name %></p></div>
      <div><p><%= f[:start_date].in_time_zone("EST").strftime("%b %e, %H:%M") %></p></div>
        <%= link_to bottle_feeding_path(f[:id], location: :home, baby_id: @baby.id), method: :delete do %>
          <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
        <% end %>
    <% elsif f[:type] == "boob"%>
      <div><img src="<%= image_path('breast.svg') %>" alt="" style="width:30px"></div>
      <div><p><%= f[:duration_minutes] %></p></div>
      <div><p><%= User.find(f[:user_id]).name %></p></div>
      <div><p><%= f[:start_date].in_time_zone("EST").strftime("%b %e, %H:%M") %></p></div>
        <%= link_to breast_feeding_path(f[:id], location: :home, baby_id: @baby.id), method: :delete do %>
          <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
        <% end %>
    <% elsif f[:type] == "diaper" %>

      <div><img src="<%= image_path('diaper.svg') %>" alt="" style="width:30px"></div>
      <div><p><%= f[:category] %></p></div>
      <div><p><%= User.find(f[:user_id]).name %></p></div>
      <div><p><%= f[:start_date].in_time_zone("EST").strftime("%b %e, %H:%M") %></p></div>
      <%= link_to diaper_path(f[:id], location: :home, baby_id: @baby.id), method: :delete do %>
        <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
      <% end  %>
    <% elsif f[:type] == "sleep" %>

      <div><img src="<%= image_path('moon.svg') %>" alt="" style="width:30px"></div>

      <div><p><%= f[:sleep_time] %> min</p></div>
      <div><p><%= User.find(f[:user_id]).name %></p></div>


      <div><p><%= f[:start_date].in_time_zone("EST").strftime("%b %e, %H:%M") %></p></div>
      <%= link_to sleep_path(f[:id], location: :home, baby_id: @baby.id), method: :delete do %>

        <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
      <% end %>

      <% elsif f[:type] == "mood" %>

      <div><img src="<%= image_path('give.svg') %>" alt="" style="width:30px"></div>

      <div><p><%= f[:category] %></p></div>
      <div><p><%= User.find(f[:user_id]).name %></p></div>


      <div><p><%= f[:start_date].in_time_zone("EST").strftime("%b %e, %H:%M") %></p></div>
      <%= link_to mood_path(f[:id], location: :home, baby_id: @baby.id), method: :delete do %>

        <div><img src="<%= image_path('close.svg') %>" alt="" style="width:15px"></div>
      <% end %>
    <% end %>
  </div>
  <hr>
<% end %>